qxwidget: TinyTabBar: optimize private inheritance
When TinyNavBarPrivate define Q_DECLARE_PUBLIC(TinyNavBar), need to know
the full definition of TinyNavBar. Otherwise, the following error is reported:
---
tinynavbar_p.h:24:5:
error: static_cast from 'QxWidget::TinyTabBar *' to 'QxWidget::TinyNavBar *',
       which are not related by inheritance, is not allowed
qglobal.h:1152:37: note: expanded from macro 'Q_DECLARE_PUBLIC'
tinynavbar_p.h:18:7: note: 'TinyNavBar' is incomplete
tinytabbar_p.h:17:7: note: 'TinyTabBar' is incomplete
---

In addition, the private base class (e.g., TinyTabBarPrivate) needs to define the
public QX_DECLARE_PUBLIC so that the main inheritance class (e.g., TinyNavBar)
can call setPublic through d (e.g., TinyNavBarPrivate).

Signed-off-by: canpool <canpool@163.com>